apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-ipfs
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`${INGRESS_HOST}`) && PathPrefix(`/api`)
    services:
    - kind: Service
      name: ipfs-node
      port: 5001
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gateway-ipfs
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`${INGRESS_HOST}`) && PathPrefix(`/ipfs`)
    services:
    - kind: Service
      name: ipfs-node
      port: 8080
  tls:
    secretName: tls-secret
